# $Id$

SUBDIR=\
	dahdi\
	dahdi_dynamic\
	dahdi_dynamic_loc\
	dahdi_dynamic_eth\
	dahdi_dynamic_ethmf\
	dahdi_echocan_jpah\
	dahdi_echocan_kb1\
	dahdi_echocan_mg2\
	dahdi_echocan_sec\
	dahdi_echocan_sec2\
	dahdi_fw_oct6114_064\
	dahdi_fw_oct6114_128\
	dahdi_voicebus\
	ng_dahdi_netdev\
	wcb4xxp\
	wct4xxp\
	wctdm24xxp

.include <bsd.subdir.mk>
